# Generated by Django 5.1.2 on 2024-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Cardiovascular', 'Cardiovascular')], default='Strength', max_length=255),
        ),
    ]
