# Generated by Django 5.1.2 on 2024-10-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cardiovascular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(blank=True)),
                ('time', models.PositiveIntegerField()),
                ('calories_burnt', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiovascular_exercises', to='api.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.PositiveIntegerField()),
                ('rep', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strength_exercises', to='api.exercise')),
            ],
        ),
    ]
