# Generated by Django 4.2 on 2024-11-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gym_alter_exercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
