# Generated by Django 4.2 on 2024-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_gym_latitude_alter_gym_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='linksAttached',
            field=models.CharField(default='', max_length=255),
        ),
    ]
